### ISSUE TITLE
Add additional commands for build and import image

### ISSUE THREAD

**Issue by djyou** [AppPlatPerf/azure-cli#145]
There are a few APIs that we don't have commands yet (the following commands are examples and can be shortened):

`acr build-task list-build-arguments`

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/build_steps_operations.py#L511

`acr build-task list-source-repository-properties`

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/build_tasks_operations.py#L494

`acr build-task update-build`

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/builds_operations.py#L249

`acr build-task cancel`

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/builds_operations.py#L411

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by djyou** [comment]
Yes it updates if the build is/will be archived.

**Comment by xiadu94** [comment]
Then maybe "acr build-task update-build" is no needed here since there is already an "acr build-task update" calling the same sdk API?

**Comment by djyou** [comment]
They are three different things.

update build task
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/build_tasks_operations.py#L438

update build step
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/build_steps_operations.py#L449

update build
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/operations/builds_operations.py#L249

**Comment by xiadu94** [comment]
#https://github.com/Azure/azure-cli/pull/6832

merged and close
