### ISSUE TITLE
Enable limiting the number of manifests shown by "az acr repository show-manifest" command

### ISSUE THREAD

**Issue by sajayantony** [AppPlatPerf/azure-cli#150]
**Is your feature request related to a problem? Please describe.**
Currently show manifests doesn't limit the number of images returned. 

**Describe the solution you'd like**
Show manifest should be sorted by time and only return the number requested. 
When customers have large number of images in their repository, we might end up making a large number of requests to the server and this needs to reduce or have a default safe count.

**Comment by djyou** [comment]
This support has been merged in. Closing issue.
