### ISSUE TITLE
New ACR runtime commands for managing metadata/attributes/etc.

### ISSUE THREAD

**Issue by djyou** [AppPlatPerf/azure-cli#158]
ACR currently has a few commands under `acr repository` group to support runtime operations.

list/show commands:
```
az acr repository list -n MyRegistry
az acr repository show-manifests -n MyRegistry --repository MyRepository
az acr repository show-tags -n MyRegistry --repository MyRepository
```

delete commands:
```
az acr repository delete -n MyRegistry --repository MyRepository
az acr repository delete -n MyRegistry --image MyRepository:MyTag
az acr repository delete -n MyRegistry --image MyRepository@MyDigest
az acr repository untag -n MyRegistry --image MyRepository:MyTag
```

We are in the process of shipping a richer set of information (aka, runtime metadata APIs) for each repository/manifest/tag.

**Proposal 1**
Add `--detail` on top of existing list/show commands that will call the new metadata APIs:
```
az acr repository list -n MyRegistry --detail
az acr repository show-manifests -n MyRegistry --repository MyRepository --detail
az acr repository show-tags -n MyRegistry --repository MyRepository --detail
```

Metadata  set/get/list with filter style:
```
az acr repository set-metadata -n MyRegistry --repository MyRepository (for repository)
az acr repository set-metadata -n MyRegistry --image MyRepository:MyTag (for tag)
az acr repository set-metadata -n MyRegistry --image MyRepository@MyDigest (for manifest)
```
`get-metadata` and `list-metadata` are similar.

Attributes set/get with filter style:
```
az acr repository set-attributes -n MyRegistry --repository MyRepository (for repository)
az acr repository set-attributes -n MyRegistry --image MyRepository:MyTag (for tag)
az acr repository set-attributes -n MyRegistry --image MyRepository@MyDigest (for manifest)
```
`get-attributes ` is similar.

**Proposal 2**
Surface managing repository/manifest/tag as different entities with new commands. Existing commands stay the same.

For `repository`:
```
az acr repository list -r MyRegistry
az acr repository show -r MyRegistry -n MyRepository (get repository attributres)
az acr repository delete -r MyRegistry -n MyRepository
az acr repository update -r MyRegistry -n MyRepository (update repository attributes)
az acr repository set-metadata -r MyRegistry -n MyRepository
az acr repository get-metadata -r MyRegistry -n MyRepository
az acr repository list-metadata -r MyRegistry -n MyRepository
```

For `manifest` and `tag` (use `manifest` as examples):
```
az acr repository manifest list -r MyRegistry -n MyRepository
az acr repository manifest show -r MyRegistry -n MyManifestDigest (get manifest attributes)
az acr repository manifest delete -r MyRegistry -n MyManifestDigest
az acr repository manifest update -r MyRegistry -n MyManifestDigest (update manifest attributes)
az acr repository manifest set-metadata -r MyRegistry -n MyManifestDigest
az acr repository manifest get-metadata -r MyRegistry -n MyManifestDigest
az acr repository manifest list-metadata -r MyRegistry -n MyManifestDigest
```
Can also be shortened to `az acr manifest ...`.

Thoughts? 
/cc @yuwaMSFT2 @sajayantony @northtyphoon @SteveLasker

**Comment by yuwaMSFT2** [comment]
Proposal 2 seems more clear on intention to me.

**Comment by northtyphoon** [comment]
Proposal 2 seems following CLI guidance so I vote for it. I have a couple of questions about the commands and options.
1. I'm wondering if get-XYZ, list-XYZ and show-XYZ can be merged? I'm not sure if it's common pattern in CLI. In Powershell version, Get-XYZ by default returns the list. If I add name or id filter it returns the specified item. If I add detail option if available, it returns more details. If CLI already has a clear guidance on it, can anyone point it to me? 

2. I'd like to understand why Proposal 2 choose two command set to handle attribute and metadata separately and why attribute is through entity get/update command directly. Is it because they're accessible by two set of APIs?

**Comment by djyou** [comment]
1. The pattern in Az CLI is to use `entity list` for an array of entities and `entity show` for an entity. `show-entity` style is usually used when entity doesn't have enough commands to form a command group. Az CLI doesn't have the same pattern as Powershell, but the closest one to this style is like `acr list` (list by subscription) vs. `acr list -g` (list by resource group). Another concern specifically here is that attributes list and get will have different fields, where get has more details.
2. Attributes are more of properties of an entity here that are defined by system and may or may not be editable to users, while metadata are additional customized key-value pairs that are accessed through different APIs.

**Comment by sajayantony** [comment]
Manifest show and manifest inspect need to be considered. Docker CLI has a manifest inspect which actually fetches the manifest itself. 
`az acr repository manifest inspect [repo:tag|repo@digest]`
I'm guessing manifest show aligns with update and inspect aligns with Docker?
Also for metadata have we considered moving it out 

`az acr repository metadata set  -t [repo|repo:tag|repo@digest]. key=value key=value` 
`az acr repository metadata list -t [repo|repo:tag|repo@digest]` 
`az acr repository metadata show -t [repo|repo:tag|repo@digest] keyName` 

similarly for `attributes`

All this with positional args if possible.

**Comment by djyou** [comment]
@sajayantony This style aligns with the one in proposal 1, basically the parameters of `repository` and `image` are used to filter the target entity.
```
az acr repository metadata set -t [repo:tag|repo@digest]. key=value key=value
az acr repository set-metadata -t [repo:tag|repo@digest]. key=value key=value

az acr repository metadata set --repository [repo]. key=value key=value
az acr repository set-metadata --repository [repo]. key=value key=value
```
One minor thing is that we default `repo` to `repo:latest` so `--image` needs to be separated from `--repository`. This style also aligns well with the existing delete commands.

@northtyphoon I thought more about your comments on managing repository/manifest/tag/image as first class entities.

```
az acr docker-entity operation
```
For example,
```
az acr repository delete --repository [repo]
az acr repository delete -t [repo:tag|repo@digest]
```

`metadata` can be in either a group or as a verb-metadata style:
```
az acr manifest metadata set 
az acr manifest set-metadata
```

Having one command for delete but determine the target from specified parameters:
```
az acr repository delete -t [repo:tag|repo@digest]
az acr repository delete --repository [repo]
```
