### ISSUE TITLE
az acr build --no-push command fails

### ISSUE THREAD

**Issue by sajayantony** [AppPlatPerf/azure-cli#161]
**Describe the bug**
--no-push on quick build with positional arguments fails. 

**To Reproduce**
```
az acr build -r sajayeus --no-push .
az acr build: '.' is not an az acr build command. See 'az acr build --help'.
```
**Expected behavior**
Build should be scheduled and image should not be pushed.

**Comment by djyou** [comment]
This is a CLI arg parsing issue, I will redirect to CLI team. Use the following to unblock you:
```
az acr build -r sajayeus . --no-push
```
