### ISSUE TITLE
Unify --image parameter used in different commands

### ISSUE THREAD

**Issue by djyou** [AppPlatPerf/azure-cli#163]
`-t` should be supported where `--image` is used to specify an image by tag or by digest. Descriptions should be shared to avoid confusion.

```
az acr import --image/-t [repo:tag]
az repository delete --image/-t [repo:tag|repo@digest]
az repository untag --image/-t [repo:tag]
az acr build --image/-t [repo:tag]
az acr build-task create/update --image/-t [repo:tag]
```

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by djyou** [comment]
FYI @NatalieGong @northtyphoon @sajayantony

**Comment by ehotinger** [comment]
can we make a breaking change and do `--tag` instead of `--image` for 100% consistency

e: I guess that's a bad idea for the old commands, but for `build` it makes sense to me

**Comment by djyou** [comment]
`--tag` is already taken by ARM tags.
