### ISSUE TITLE
Design Policy commands.

### ISSUE THREAD

**Issue by ankurkhemani** [AppPlatPerf/azure-cli#166]
**Proposal 1**
Group all policies together under `az acr policy` command group.

`az acr policy show -n <registry_name> --type Trust` 
(If no type is specified, show entire policy object)

`az acr policy update -n <registry_name> --type Trust --enabled False`
(Updates a particular type of policy)

**Pros**: Just one `policy `command group, easy to manage.
**Cons**: 
1. Could be hard to scale with too many arguments for update as we keep adding different policies.
2. Update can be confusing (might be an anti-pattern) since each policy is a different object with some common members like "enabled". We would also need to validate arguments allowed for a particular policy type (error thrown later), which could be a bad user experience.

Another approach can be to allow update for all policy types (without any `--type` argument), and prefix argument names with the type. For example, argument ` --enabled` becomes `--trust-enabled`, `--quarantine-enabled` and `--purge-enabled`.

`az acr policy update -n <registry_name> --trust-enabled True --quarantine-enabled False`
(Can update all policies, still hard to scale?)

**Proposal 2**
Add separate command groups for each policy and handle them separately like Portal does.

```
az acr trust show -n <registry_name>
az acr trust update -n <registry_name> --enabled True

az acr quarantine show -n <registry_name>
az acr quarantine update -n <registry_name> --enabled True --enforced False

az acr purge show -n <registry_name>
az acr purge update -n <registry_name> --enabled True --delete-untagged-images True
```
and so on..

**Pros**: less confusing, can scale better.
**Cons**: Adds many command groups (think Nodes on Portal).

EDIT: An extension to Proposal 2 would be to have these command groups under `policy` command group viz `az acr policy content-trust`, `az acr policy purge`, etc to prevent having too many command groups under `az acr`

Thoughts? @sajayantony @djyou @SteveLasker @sivagms

**Comment by sivagms** [comment]
I vote for proposal 2 - seems more intuitive to me.

**Comment by sajayantony** [comment]
`az acr policy content-trust show`
`az acr policy purge update --set delete-untagged-images enabled`

or should we make it. 

`az acr content-trust show` 
`az acr purge-policy show`

@SteveLasker

**Comment by sivagms** [comment]
the commands in proposal 2 could be more descriptive , such as content-trust and autopurge

**Comment by yuwaMSFT2** [comment]
Like the one mentioned by Sajay:
az acr policy content-trust show
az acr policy purge update --set delete-untagged-images enabled

It's more clear that these are policy commands. Is there any issue with this?

**Comment by djyou** [comment]
Proposal 2 overwhelms the number of commands under `az acr` but proposal 1 is very confusing. I agreed with Yu/Sajay's proposal.

More thoughts on the show command, we have one API that returns the entire policies json, maybe we can unify show to one command:

`az acr policy show`
`az acr policy update-content-trust` vs. `az acr policy content-trust update`
`az acr policy update-purge` vs. `az acr policy purge update`
`az acr policy update-quarantine` vs. `az acr policy quarantine update`

Otherwise on each individual show you will have to trim the json on the client side.

**Comment by sivagms** [comment]
as a user i'd probably prefer typing less. 'policy' command seems redundant.  Moreover, content-trust doesn't seem to be a policy to me. Once it is enabled, it is an optional feature that docker client chooses..

**Comment by ankurkhemani** [comment]
So after discussion with @SteveLasker and @sajayantony, we landed on:

```
az acr config content-trust show ..
az acr config content-trust update ..

az acr config quarantine show ..
az acr config quarantine update ..

az acr config vnet show ..
az acr config vnet  update ..
```
and so on

**Comment by ankurkhemani** [comment]
Added commands for content-trust: https://github.com/Azure/azure-cli/pull/6912
