### ISSUE TITLE
[Discuss] CLI param names

### ISSUE THREAD

**Issue by ehotinger** [AppPlatPerf/azure-cli#230]
IE:

`--task`, `--values` vs. `--task-file`, `--values-file`, ...

acb and CLI should be consistent

**Comment by ehotinger** [comment]
After discussion: rename to `-f`, no more `--task-file`; use  `--values`

**Comment by ankurkhemani** [comment]
@sajayantony @ehotinger @SteveLasker Can you help listing all the reserved task file types (".yaml", etc)?

**Comment by ehotinger** [comment]
Scripting languages:
- ts
- js
- php
- py
- rb
- lua

Shells:
- sh
- bash
- zsh
- ps1
- ps (is this valid?)

Formats:
- yaml
- toml
- json

**Comment by sajayantony** [comment]
Include cmd/bat as well.
