### ISSUE TITLE
[Helm] acr helm command group

### ISSUE THREAD

**Issue by djyou** [AppPlatPerf/azure-cli#244]
The new command group:
```
Group
    az acr helm : Manage helm charts for Azure Container Registries.

Subgroups:
    repo   : Manage helm chart repositories for Azure Container Registries.

Commands:
    delete : Delete a helm chart version in a container registry.
    list   : List all helm charts in a container registry.
    push   : Push a helm chart package to a container registry.
    show   : Describe a helm chart version in a container registry.
```

`az acr helm repo add` is a wrapper of `helm repo add` and ll other commands call APIs directly (assuming the default `acr` is set so `-n MyRegistry` is omitted in the following examples):

|Action|Command|
|:-------|:----------|
|Login to a repo|`az acr helm repo add`|
|Push a chart|`az acr helm push mychart-0.3.2.tgz`|
|List all charts|`az acr helm list`|
|List all versions of a chart|`az acr helm show mychart`|
|Describe a version of a chart|`az acr helm show mychart --version 0.3.2`|
|Delete all versions of a chart|`az acr helm delete mychart`|
|Delete a version of a chart|`az acr helm delete mychart --version 0.3.2`|

All commands have an optional `--repository` that currently defaults to `repo`.

**Comment by djyou** [comment]
Feedback appreciated, mostly on whether `mychart` is a positional argument or not. /cc @SteveLasker @sajayantony @yuwaMSFT2 @ehotinger @northtyphoon

**Comment by ehotinger** [comment]
makes sense to me as a positional arg; I think any core artifact that is required to run the commands should be positional args just to 1) enforce it's required and get the nice CLI usage; 2) reduce typing

**Comment by sajayantony** [comment]
This makes sense and I think we will default to positional args for all chart commands.
