### ISSUE TITLE
avoid hard coding azurecr.io in output

### ISSUE THREAD

**Issue by northtyphoon** [AppPlatPerf/azure-cli#269]
run `az acr run` command against dogfood registry (azurecr-test.io) and see the output

`Sending context (386.000 Bytes) to acrbuilddemo.azurecr.io...`

**Comment by ehotinger** [comment]
Maybe we can just remove the suffix and change the wording to "Sending context [x] to registry: acrbuilddemo". `-r` doesn't have this information and it seems excessive to query for it.

NB: this has to be changed in multiple places.

**Comment by northtyphoon** [comment]
I think It's totally fine to just output registry name.
