### ISSUE TITLE
Remove Platform from client

### ISSUE THREAD

**Issue by ehotinger** [AppPlatPerf/azure-cli#75]
Similar to #74 - remove Platform from the client as well. AKA: don't always default to Linux.

PS: make sure to verify the server side can put in the default value for this as well.

**Comment by djyou** [comment]
So either (1) make `os_type` in `Platform` an optional parameter with a default value (current implementation, also preferred behavior IMO); or (2) make it mandatory without a default value.

**Comment by ehotinger** [comment]
Closed, not relevant anymore.
