### ISSUE TITLE
CLI refuses to accept build

### ISSUE THREAD

**Issue by ehotinger** [AppPlatPerf/azure-cli#79]
On Windows, using PowerShell:

```
git clone https://github.com/steveLasker/aspnetcore-helloworld
cd aspnetcore-helloworld
az acr build -t aspnetcore-helloworld:v1 -f ./HelloWorld/Dockerfile -c . -r acrbuilddemoeus
```

also using .\HelloWorld\Dockerfile as expected in Windows doesn't work

Response:
`name 'docker_file_path' is not defined`

**Comment by NatalieGong** [comment]
On my side, the error message suggests "'RegistriesOperations' object has no attribute 'get_build_source_upload_url'" both for prod cloud and internal test cloud.

**Comment by NatalieGong** [comment]
Oh here is the error message:
C:\git\aspnetcore-helloworld>az acr build -t aspnetcore-helloworld:v1 -f ./HelloWorld/Dockerfile -c . -r acrbuilddemoeus
'RegistriesOperations' object has no attribute 'get_build_source_upload_url'

**Comment by NatalieGong** [comment]
Oh Acutally Ankur helped me solve my error message already!

**Comment by NatalieGong** [comment]
And now I am getting the same error message as you did

**Comment by NatalieGong** [comment]
name 'docker_file_path' is not defined

**Comment by ehotinger** [comment]
BTW, possible that this is a broken build. I redeployed the latest bits on Linux and it works for me. Still need to verify on Win.
