### ISSUE TITLE
Fix columns for List-builds 

### ISSUE THREAD

**Issue by sajayantony** [AppPlatPerf/azure-cli#87]
1. Remove task name when there is no task 
2. Keep duration as  hh:mm:ss as before 

ID | TASK | PLATFORM | STATUS | STARTED | DURATION |
|---------|-------|------------|---------|-----------|-------------|
eastus-2 | testask | Linux | Succeeded | 2018-04-06T19:02:04Z| 00:00:30
eastus-1 |             | Linux | Succeeded | 2018-04-06T19:02:04Z| 00:10:00

ref - https://github.com/Azure/azure-cli/pull/6040

**Comment by djyou** [comment]
This PR https://github.com/Azure/azure-cli/pull/6040 has been merged. The PR https://github.com/AzureCR/azure-cli/pull/95 addressed the updated `TASK` field. The remaining work is on `TRIGGER` (image update and git commit).

**Comment by djyou** [comment]
Close as this has been fixed.
